apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    kubernetes.io/name: {{ .Chart.Name }}-service
    app: {{ .Chart.Name }}-service
spec:
  selector:
    app: {{ .Chart.Name }}-service
  ports:
  - name: ocr-port
    port: 5000